# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-06 00:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0002_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado_pago', models.IntegerField()),
                ('estado_trabajo', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('detalle_monto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta_contable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Ejecuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.IntegerField()),
                ('observacion', models.TextField()),
                ('nota', models.IntegerField(choices=[(5, 'Muy Bien'), (4, 'Bien'), (3, 'Suficiente'), (2, 'Mal'), (1, 'Muy Mal')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estructura_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_2', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('documento_externo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cotizaciones', models.ManyToManyField(to='erp.Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cotizaciones', models.ManyToManyField(to='erp.Cotizacion')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('direccion_comercial', models.CharField(max_length=200)),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('sueldo_base', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_termino_contrato', models.DateField()),
                ('horas_semanales', models.IntegerField()),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cuenta_contable')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('observacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Actividad')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cotizacion')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cuadrilla')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.OT')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Material')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Trabajo')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_factura',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='numero_factura',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 6, 0, 44, 29, 870309, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_comercial',
            field=models.CharField(default='Santiago', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro',
            field=models.CharField(default='Comercializadora', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacion',
            field=models.TextField(default='Hola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='Papa Johns', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 6, 0, 45, 57, 238181, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 6, 0, 46, 8, 131010, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='neto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='observacion',
            field=models.TextField(default='o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 6, 0, 46, 37, 460827, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='pago',
            name='facturas',
            field=models.ManyToManyField(to='erp.Factura'),
        ),
        migrations.AddField(
            model_name='local',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cliente'),
        ),
        migrations.AddField(
            model_name='encargado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cliente'),
        ),
        migrations.AddField(
            model_name='ejecuta',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Trabajador'),
        ),
        migrations.AddField(
            model_name='ejecuta',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Trabajo'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Material'),
        ),
        migrations.AddField(
            model_name='cuenta_contable',
            name='estructura_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Estructura_costo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='facturas',
            field=models.ManyToManyField(to='erp.Factura'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Local'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Trabajador'),
        ),
    ]
