# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20170805_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='numero',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_pago',
            field=models.IntegerField(choices=[(1, 'Esperando'), (2, 'Trabajando'), (3, 'Terminado')]),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_trabajo',
            field=models.IntegerField(choices=[(1, 'Cotizado'), (2, 'Facturado'), (3, 'En Espera'), (4, 'Pagado'), (5, 'Atraso')]),
        ),
        migrations.AlterField(
            model_name='local',
            name='nombre_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
