# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20170916_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='utilizado',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='utilizado',
            name='material',
        ),
        migrations.RemoveField(
            model_name='utilizado',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='utilizado',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Cotizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilizado',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='utilizado',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.IntegerField(choices=[(1, 'En Espera'), (2, 'Debe'), (3, 'Pendiente Facturacion'), (4, 'Facturada')], default=1),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_trabajo',
            field=models.IntegerField(choices=[(1, 'Esperando'), (2, 'Trabajando'), (3, 'Terminado')], default=1),
        ),
        migrations.AddField(
            model_name='utilizado',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.Documento'),
            preserve_default=False,
        ),
    ]
