# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20170921_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='facturas',
        ),
        migrations.AddField(
            model_name='factura',
            name='cotizaciones',
            field=models.ManyToManyField(blank=True, null=True, to='erp.Cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.IntegerField(choices=[(1, 'En Espera'), (2, 'Debe'), (3, 'Por Facturar'), (4, 'Facturada')], default=1),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Documento'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Esperando'), (2, 'Trabajando')], default=1),
        ),
    ]
