# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20170929_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='neto',
        ),
        migrations.AlterField(
            model_name='factura',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
