# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20170929_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='cotizaciones',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Impaga'), (2, 'Pagada')], default=1),
        ),
    ]
