# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_auto_20171008_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='estado_trabajo',
        ),
        migrations.AlterField(
            model_name='ejecuta',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ot',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
